# Generated by Django 2.2.16 on 2020-11-27 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('keycloak-role', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='keycloakrole',
            name='keycloak_id',
            field=models.CharField(max_length=40),
        ),
    ]
