# Generated by Django 2.2.16 on 2020-11-27 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('keycloak-role', '0003_auto_20201127_0214'),
    ]

    operations = [
        migrations.AlterField(
            model_name='keycloakrole',
            name='keycloak_id',
            field=models.CharField(max_length=40, unique=True),
        ),
    ]
