# Generated by Django 2.2.16 on 2020-11-30 03:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('keycloak-role', '0005_auto_20201127_0248'),
    ]

    operations = [
        migrations.AlterField(
            model_name='keycloakrole',
            name='group',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='groups.GroupProfile'),
        ),
    ]
